// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'areaBackground': string;
  'area_background': string;
  'backButton': string;
  'back_button': string;
  'box': string;
  'btnAnswer': string;
  'btnBaiseStyle': string;
  'btn_answer': string;
  'btn_baise_style': string;
  'buttonPosition': string;
  'button_position': string;
  'caption': string;
  'checkbox': string;
  'circleButton': string;
  'circle_button': string;
  'content': string;
  'customContent': string;
  'customFrame': string;
  'customNuv': string;
  'custom_content': string;
  'custom_frame': string;
  'custom_nuv': string;
  'error': string;
  'explanation': string;
  'eyeIconPosition': string;
  'eye_icon_position': string;
  'inputBox': string;
  'inputText': string;
  'input_text': string;
  'nextButton': string;
  'next_button': string;
  'selectBox': string;
  'select_box': string;
  'selectionTable': string;
  'selection_table': string;
  'subTitle': string;
  'sub_title': string;
  'textArea': string;
  'text_area': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
