// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'box': string;
  'closeButton': string;
  'close_button': string;
  'customContent': string;
  'custom_content': string;
  'downloadButton': string;
  'download_button': string;
  'ellipse': string;
  'error': string;
  'infoComment': string;
  'infoIcon': string;
  'info_comment': string;
  'info_icon': string;
  'item': string;
  'scrollContainer': string;
  'scroll_container': string;
  'selectionTable': string;
  'selection_table': string;
  'tableButtonBox': string;
  'tableHeader': string;
  'table_button_box': string;
  'table_header': string;
  'title': string;
  'titleInChatView': string;
  'title_in_chat_view': string;
}
declare var cssExports: CssExports;
export = cssExports;
