// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backButton': string;
  'back_button': string;
  'btnApply': string;
  'btnBaiseStyle': string;
  'btnBorderRadius': string;
  'btnGry': string;
  'btnMargin': string;
  'btn_apply': string;
  'btn_baise_style': string;
  'btn_border_radius': string;
  'btn_gry': string;
  'btn_margin': string;
  'componentBorder': string;
  'component_border': string;
  'customloaderParent': string;
  'description': string;
  'descriptionDiv': string;
  'descriptionInner': string;
  'divArea': string;
  'div_area': string;
  'ellipse': string;
  'scrollContainer': string;
  'tabBox': string;
  'tabBtn': string;
  'tabBtnGry': string;
  'tabDivArea': string;
  'tab_box': string;
  'tab_btn': string;
  'tab_btn_gry': string;
  'tab_div_area': string;
  'textArea': string;
  'text_area': string;
  'tooltips': string;
  'tooltipsText': string;
  'tooltips_text': string;
}
declare var cssExports: CssExports;
export = cssExports;
