// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'editButton': string;
  'edit_button': string;
  'viewerHeader': string;
}
declare var cssExports: CssExports;
export = cssExports;
