// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btnBaiseStyle': string;
  'btnGry': string;
  'btn_baise_style': string;
  'btn_gry': string;
  'tab': string;
}
declare var cssExports: CssExports;
export = cssExports;
