// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'mapFitButton': string;
  'map_fit_button': string;
}
declare var cssExports: CssExports;
export = cssExports;
