// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'applyTypeDivArea': string;
  'applyType_div_area': string;
  'backButton': string;
  'back_button': string;
  'btnApply': string;
  'btnBaiseStyle': string;
  'btnBorderRadius': string;
  'btnGry': string;
  'btnMargin': string;
  'btn_apply': string;
  'btn_baise_style': string;
  'btn_border_radius': string;
  'btn_gry': string;
  'btn_margin': string;
  'componentBorder': string;
  'component_border': string;
  'customRadio': string;
  'custom_radio': string;
  'customloaderParent': string;
  'divArea': string;
  'div_area': string;
  'radioInput': string;
  'radioLabel': string;
  'radio_input': string;
  'radio_label': string;
  'textArea': string;
  'text_area': string;
  'tooltips': string;
}
declare var cssExports: CssExports;
export = cssExports;
