// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'center': string;
  'customContent': string;
  'customFrame': string;
  'customNuv': string;
  'custom_content': string;
  'custom_frame': string;
  'custom_nuv': string;
}
declare var cssExports: CssExports;
export = cssExports;
