// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backButton': string;
  'back_button': string;
  'box': string;
  'btnBaiseStyle': string;
  'btnGry': string;
  'btn_baise_style': string;
  'btn_gry': string;
  'caption': string;
  'checkbox': string;
  'circleButton': string;
  'circle_button': string;
  'content': string;
  'customContent': string;
  'customFrame': string;
  'customNuv': string;
  'custom_content': string;
  'custom_frame': string;
  'custom_nuv': string;
  'divArea': string;
  'div_area': string;
  'error': string;
  'explanation': string;
  'inputText': string;
  'input_text': string;
  'nextButton': string;
  'next_button': string;
  'scrollContainer': string;
  'selectBox': string;
  'select_box': string;
  'selectionTable': string;
  'selection_table': string;
  'subTitle': string;
  'sub_title': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
