// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'animate-stripes': string;
  'animateStripes': string;
  'dliRedo': string;
  'dli_redo': string;
  'icon': string;
  'popupArrow': string;
  'popupContainer': string;
  'popupContent': string;
  'popup_arrow': string;
  'popup_container': string;
  'popup_content': string;
  'retryButton': string;
  'retryContainer': string;
  'retry_button': string;
  'retry_container': string;
  'uiLabel': string;
  'uiProgress': string;
  'uiProgressBar': string;
  'uiProgressWarn': string;
  'ui_label': string;
  'ui_progress': string;
  'ui_progress_bar': string;
  'ui_progress_warn': string;
}
declare var cssExports: CssExports;
export = cssExports;
