// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'customCheckbox': string;
  'customNuv': string;
  'customRadio': string;
  'custom_checkbox': string;
  'custom_nuv': string;
  'custom_radio': string;
  'downloadButton': string;
  'download_button': string;
  'modal': string;
  'overlay': string;
  'radioDivArea': string;
  'radioInput': string;
  'radioLabel': string;
  'radio_div_area': string;
  'radio_input': string;
  'radio_label': string;
  'selectionTable': string;
  'selection_table': string;
  'tableHeader': string;
  'table_header': string;
}
declare var cssExports: CssExports;
export = cssExports;
