// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addressBtn': string;
  'address_btn': string;
  'answerContentArea': string;
  'answerContentDiv': string;
  'answer_content_area': string;
  'checked': string;
  'closeButton': string;
  'close_button': string;
  'customNuv': string;
  'customSelection': string;
  'custom_nuv': string;
  'custom_selection': string;
  'detailsButton': string;
  'details_button': string;
  'downloadButton': string;
  'download_button': string;
  'ellipse': string;
  'inputMessageArea': string;
  'input_message_area': string;
  'listItem1': string;
  'listItem2': string;
  'list_item1': string;
  'list_item2': string;
  'mesageAddress': string;
  'mesage_address': string;
  'otherMesage': string;
  'otherMesageContent': string;
  'other_mesage': string;
  'other_mesage_content': string;
  'selectionTable': string;
  'selection_table': string;
  'selfMesage': string;
  'selfMesageContent': string;
  'self_mesage': string;
  'self_mesage_content': string;
  'tableHeader': string;
  'table_header': string;
}
declare var cssExports: CssExports;
export = cssExports;
