// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'box': string;
  'circleButton': string;
  'circle_button': string;
  'customFrame': string;
  'custom_frame': string;
}
declare var cssExports: CssExports;
export = cssExports;
