// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'box': string;
  'customButton': string;
  'customContent': string;
  'customFooter': string;
  'customFrame': string;
  'customNuv': string;
  'customTitle': string;
  'custom_button': string;
  'custom_content': string;
  'custom_footer': string;
  'custom_frame': string;
  'custom_nuv': string;
  'custom_title': string;
  'description': string;
  'result': string;
  'selectionTable': string;
  'selection_table': string;
  'tableFrame': string;
  'table_frame': string;
  'title': string;
  'tooltips': string;
  'trButton': string;
  'tr_button': string;
  'trashButton': string;
  'trash_button': string;
}
declare var cssExports: CssExports;
export = cssExports;
