// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backButton': string;
  'back_button': string;
  'editButton': string;
  'edit_button': string;
  'saveButton': string;
  'save_button': string;
}
declare var cssExports: CssExports;
export = cssExports;
