// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contentCol': string;
  'content_col': string;
  'customButton': string;
  'customFrame': string;
  'custom_button': string;
  'custom_frame': string;
  'districtListTable': string;
  'districtListTableRow': string;
  'districtListTableWrapper': string;
  'district_list_table': string;
  'district_list_table_row': string;
  'district_list_table_wrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
