// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'boxInputArea': string;
  'box_input_area': string;
  'clearButton': string;
  'clear_button': string;
  'customContent': string;
  'customFrame': string;
  'customNuv': string;
  'custom_content': string;
  'custom_frame': string;
  'custom_nuv': string;
  'districtListTable': string;
  'districtListTableRow': string;
  'districtNameArea': string;
  'district_list_table': string;
  'district_list_table_row': string;
  'district_name_area': string;
  'kanaCell': string;
  'kanaCellEmpty': string;
  'kanaKeyboardArea': string;
  'kanaRow': string;
  'kana_cell': string;
  'kana_cell_empty': string;
  'kana_keyboard_area': string;
  'kana_row': string;
  'selectBtnArea': string;
  'select_btn_area': string;
}
declare var cssExports: CssExports;
export = cssExports;
