// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'contentDiv': string;
  'customNuv': string;
  'custom_nuv': string;
  'listItem': string;
  'list_item': string;
  'modal': string;
  'overlay': string;
  'selectedButton': string;
  'selected_button': string;
  'selectionTable': string;
  'selection_table': string;
  'tableHeader': string;
  'tableScroll': string;
  'table_header': string;
  'table_scroll': string;
  'textAlignLeft': string;
  'textArea': string;
  'text_align_left': string;
  'text_area': string;
}
declare var cssExports: CssExports;
export = cssExports;
