// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'customNuv': string;
  'custom_nuv': string;
  'fileUploadButton': string;
  'file_upload_button': string;
  'modal': string;
  'overlay': string;
  'scrollContainer': string;
  'selectionTable': string;
  'selection_table': string;
  'tableHeader': string;
  'table_header': string;
  'uploadButton': string;
  'uploadPcButton': string;
  'upload_button': string;
  'upload_pc_button': string;
}
declare var cssExports: CssExports;
export = cssExports;
