// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'customNuv': string;
  'custom_nuv': string;
  'downloadButton': string;
  'download_button': string;
  'modal': string;
  'overlay': string;
  'selectionTable': string;
  'selection_table': string;
  'tableHeader': string;
  'table_header': string;
}
declare var cssExports: CssExports;
export = cssExports;
