// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'confirmButton': string;
  'container': string;
  'customNuv': string;
  'custom_nuv': string;
  'modal': string;
  'overlay': string;
  'scrollContainer': string;
}
declare var cssExports: CssExports;
export = cssExports;
