// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'editButton': string;
  'edit_button': string;
  'modal': string;
  'overlay': string;
  'pdfViewer': string;
  'pdf_viewer': string;
  'toolButton': string;
  'tool_button': string;
  'viewerHeader': string;
}
declare var cssExports: CssExports;
export = cssExports;
