// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'answerInputButton': string;
  'answer_input_button': string;
  'btnBaiseStyle': string;
  'btn_baise_style': string;
  'buttonDiv': string;
  'button_div': string;
  'container': string;
  'customNuv': string;
  'customRadio': string;
  'custom_nuv': string;
  'custom_radio': string;
  'modal': string;
  'overlay': string;
  'radioDiv': string;
  'radioInput': string;
  'radioLabel': string;
  'radio_input': string;
  'radio_label': string;
}
declare var cssExports: CssExports;
export = cssExports;
