// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn--catalog': string;
  'btnCatalog': string;
  'btnCatalogTopLevel': string;
  'caret': string;
  'folder': string;
  'offsetRight': string;
  'root': string;
}
declare var cssExports: CssExports;
export = cssExports;
