// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dataCatalogItem': string;
  'dataCatalogItemChild': string;
  'initButton': string;
  'initButtonArea': string;
  'init_button': string;
  'init_button_area': string;
  'layerItemListArea': string;
  'layer_item_list_area': string;
  'settingButton': string;
  'setting_button': string;
}
declare var cssExports: CssExports;
export = cssExports;
