// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrowButton': string;
  'arrow_button': string;
  'container': string;
  'customNuv': string;
  'custom_nuv': string;
  'layerLegendPostion': string;
  'layer_legend_postion': string;
  'legends': string;
  'modal': string;
  'overlay': string;
  'scrollContainer': string;
  'selectionTable': string;
  'selection_table': string;
}
declare var cssExports: CssExports;
export = cssExports;
