// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButton': string;
  'action_button': string;
  'applicantInformationBox': string;
  'applicantStatusBox': string;
  'applicantStatusBoxDiv': string;
  'applicant_information_box': string;
  'applicant_status_box': string;
  'applicant_status_box_div': string;
  'box': string;
  'clearButton': string;
  'clearLeft': string;
  'clear_button': string;
  'clear_left': string;
  'closeButton': string;
  'close_button': string;
  'customContent': string;
  'customFrame': string;
  'customNuv': string;
  'custom_content': string;
  'custom_frame': string;
  'custom_nuv': string;
  'customloader': string;
  'customloaderParent': string;
  'detailButton': string;
  'detail_button': string;
  'fixedCol': string;
  'load5': string;
  'scrollContainer': string;
  'searchButton': string;
  'searchButtonBox': string;
  'search_button': string;
  'search_button_box': string;
  'selectionTable': string;
  'selection_table': string;
  'showSearchCondition': string;
  'show_search_condition': string;
  'tableHeader': string;
  'tableScroll': string;
  'table_header': string;
  'table_scroll': string;
  'trButton': string;
  'tr_button': string;
}
declare var cssExports: CssExports;
export = cssExports;
