// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButton': string;
  'action_button': string;
  'box': string;
  'caption': string;
  'circleButton': string;
  'circle_button': string;
  'closeButton': string;
  'close_button': string;
  'customContent': string;
  'customFrame': string;
  'customNuv': string;
  'custom_content': string;
  'custom_frame': string;
  'custom_nuv': string;
  'customloader': string;
  'customloaderParent': string;
  'downloadButton': string;
  'download_button': string;
  'error': string;
  'explanation': string;
  'inputText': string;
  'input_text': string;
  'item': string;
  'load5': string;
  'loader': string;
  'scrollContainer': string;
  'selectBox': string;
  'select_box': string;
  'selectionTable': string;
  'selection_table': string;
  'subTitle': string;
  'sub_title': string;
  'tableHeader': string;
  'table_header': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
