// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'applicationLotNumberPanel': string;
  'btnPanelHeading': string;
  'button': string;
  'buttonName': string;
  'button_name': string;
  'header': string;
  'loader': string;
}
declare var cssExports: CssExports;
export = cssExports;
