// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'inquiryListTable': string;
  'inquiry_list_table': string;
}
declare var cssExports: CssExports;
export = cssExports;
